print("holaaaaa")
print("holaaaaa")
print("holaaaaa")
print("holaaaaa")
print("hola mundo")
print("hola mundo")
print("hola mundo")
print("hola mundo")
print("holaaaaa")
print("holaaaaa")
print("holaaaaa")
print("holaaaaa")
print("hola mundo")
print("hola mundo")
print("hola mundo")
print("hola mundo")